apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 67.5.0
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          ingress:
            enabled: true
            hosts:
              - grafana.kacpermalachowski.pl

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true