version: '3.7'

services:
  portainer:
    image: portainer/portainer-ce:2.32.0-alpine
    command: -H unix:///var/run/docker.sock --admin-password "${PORTAINER_ADMIN_PASSWORD:-admin}"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - portainer
      - public
      - monitoring
    logging:
      options:
        max-size: "10m"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        delay: 15s
        parallelism: 1
        monitor: 10s
        failure_action: rollback
        max_failure_ratio: 0.55
      resources:
        limits:
          cpus: '0.35'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 128M
    labels:
      - "traefik.enable=true"
      # HTTP router (will be redirected to HTTPS by global redirect)
      - "traefik.http.routers.portainer-http.rule=Host(`portainer.${DOMAIN:-malachowski.me}`)"
      - "traefik.http.routers.portainer-http.entrypoints=web"
      - "traefik.http.routers.portainer-http.service=portainer"
      # HTTPS router
      - "traefik.http.routers.portainer-https.rule=Host(`portainer.${DOMAIN:-malachowski.me}`)"
      - "traefik.http.routers.portainer-https.entrypoints=websecure"
      - "traefik.http.routers.portainer-https.tls=true"
      - "traefik.http.routers.portainer-https.tls.certresolver=le"
      - "traefik.http.routers.portainer-https.service=portainer"
      - "traefik.http.routers.portainer-https.middlewares=compresstraefik,secureheaders"
      # Service definition
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.services.portainer.loadbalancer.passhostheader=true"
      # Middleware
      - "traefik.http.middlewares.compresstraefik.compress=true"
      - "traefik.http.middlewares.secureheaders.headers.sslredirect=true"
      - "traefik.http.middlewares.secureheaders.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.secureheaders.headers.stsSeconds=31536000"

  agent:
    image: portainer/agent:2.32.0-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer
      - monitoring
    logging:
      options:
        max-size: "10m"
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      update_config:
        delay: 15s
        parallelism: 1
        monitor: 10s
        failure_action: rollback
        max_failure_ratio: 0.55
      resources:
        limits:
          cpus: '0.35'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 128M

networks:
  portainer:
    driver: overlay
    attachable: true
  public:
    external: true
  monitoring:
    external: true

volumes:
  portainer_data: