- name: Initialize Swarm cluster
  hosts: swarm_manager[0]
  become: true
  tasks:
    - name: Initialize Docker Swarm
      community.docker.docker_swarm:
        state: present
        advertise_addr: "{{ ansible_ssh_host }}"
      register: swarm_init

    - name: Get join-token for manager nodes
      ansible.builtin.set_fact:
        join_token_manager: "{{ hostvars[groups['swarm_manager'][0]].JoinTokens.Manager }}"
      when: inventory_hostname in groups['swarm_manager']

    - name: Get join-token for worker nodes
      ansible.builtin.set_fact:
        join_token_worker: "{{ hostvars[groups['swarm_manager'][0]].JoinTokens.Worker }}"
      when: inventory_hostname in groups['swarm_worker']

    - name: Join manager nodes to the swarm
      community.docker.docker_swarm:
        state: join
        join_token: "{{ join_token_manager }}"
        remote_addrs: "{{ hostvars[groups['swarm_manager'][0]].ansible_host }}"
      when:
        - inventory_hostname in groups['swarm_manager']
        - inventory_hostname != groups['swarm_manager'][0]

    - name: Join worker nodes to the swarm
      community.docker.docker_swarm:
        state: join
        join_token: "{{ join_token_worker }}"
        remote_addrs: "{{ hostvars[groups['swarm_manager'][0]].ansible_host }}"
      when: inventory_hostname in groups['swarm_worker']
