- name: Deploy Traefik stack to Swarm manager
  hosts: swarm_manager[0]
  tasks:
    - name: Copy stacks to manager node
      ansible.builtin.copy:
        src: .
        dest: traefik/
        mode: '0644'

    - name: Create traefik network
      community.docker.docker_network:
        name: public
        state: present
        driver: overlay

    - name: Create monitoring network
      community.docker.docker_network:
        name: monitoring
        state: present
        driver: overlay

    - name: Install and setup traefik service
      community.docker.docker_stack:
        state: present
        name: traefik
        compose:
          - "traefik/docker-compose.yml"
      environment:
        DOMAIN: "{{ ansible_domain | default('malachowski.me') }}"
