name: apply-prod

concurrency:
  group: terraform-prod

on:
  push:
    branches:
      - main
    paths:
      - terraform/**
      - .github/workflows/apply-prod.yml
      - ansible/**
      - requirements.txt

jobs:
  apply:
    permissions:
      contents: "read" # needed for gcp_auth
      id-token: "write" # needed for gcp_auth to create id token
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_TERRAFORM_EXECUTOR_SERVICE_ACCOUNT_EMAIL }}

      - id: "secrets"
        uses: "google-github-actions/get-secretmanager-secrets@v2"
        with:
          secrets: |-
            tf-executor-gh-token:${{ vars.GCP_PROJECT_ID }}/terraform-executor-gh-token
            tf-executor-hcloud-token:${{ vars.GCP_PROJECT_ID }}/terraform-executor-hcloud-token
            tf-executor-cf-token:${{ vars.GCP_PROJECT_ID }}/terraform-executor-cloudflare-token
            tf-ssh-private-key:${{ vars.GCP_PROJECT_ID }}/terraform-ssh-private-key

      - name: Tofu Init
        run: tofu init -input=false
        working-directory: terraform/environments/prod

      - name: Tofu Apply
        run: tofu apply -input=false -no-color -lock-timeout=300s -auto-approve
        env:
          GITHUB_TOKEN: ${{ steps.secrets.outputs.tf-executor-gh-token }}
          CLOUDFLARE_API_TOKEN: ${{ steps.secrets.outputs.tf-executor-cf-token }}
          TF_VAR_hcloud_token: ${{ steps.secrets.outputs.tf-executor-hcloud-token }}
          TF_VAR_ssh_public_key: ${{ vars.TF_SSH_PUBLIC_KEY }}
          TF_VAR_ssh_private_key: ${{ steps.secrets.outputs.tf-ssh-private-key }}
        working-directory: terraform/environments/prod
