name: apply-prod

concurrency:
  group: terraform-prod

on:
  push:
    branches:
      - main
    paths:
      - terraform/**
      - .github/workflows/apply-prod.yml

jobs:
  apply:
    permissions:
      contents: "read" # needed for gcp_auth
      id-token: "write" # needed for gcp_auth to create id token
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_argo_github_token: ${{ secrets.ARGO_GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_TERRAFORM_EXECUTOR_SERVICE_ACCOUNT_EMAIL }}

      - name: Tofu Init
        run: tofu init -input=false
        working-directory: terraform/environments/prod

      - name: Tofu Apply
        run: tofu apply -input=false -no-color -lock-timeout=300s -auto-approve
        working-directory: terraform/environments/prod
