name: build-talos-hcloud-image

on:
  push:
    branches:
      - main
    paths:
      - packer/hcloud/**
      - .github/workflows/build-talos-hcloud-image.yml
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - packer/hcloud/**
      - .github/workflows/build-talos-hcloud-image.yml

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@v3

      - name: Initialize Packer
        run: packer init .
        working-directory: packer/hcloud

      - name: Validate Packer Template
        run: packer validate .
        working-directory: packer/hcloud

      - name: Build Packer Image
        run: packer build -var "snapshot_suffix=${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}" .
        working-directory: packer/hcloud
        env:
          PKR_VAR_build_source: ${GITHUB_REF_NAME}

  remove_pr_snapshot:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
    steps:
      - name: Setup Hetzner Cloud
        uses: hetznercloud/setup-hcloud@v1

      - name: Get this run snapshot ID
        id: get_snapshot_id
        run: |
          snapshot_id=$(hcloud image list -t snapshot -o json | jq '.[] | select(.description | contains("${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}")).id')
          echo "snapshot_id=$snapshot_id" >> $GITHUB_OUTPUT

      - name: Remove snapshot
        run: |
          snapshot_id=${{ steps.get_snapshot_id.outputs.snapshot_id }}
          hcloud image delete $snapshot_id
