name: clean-old-snapshots

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  clean-old-snapshots:
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
    steps:
      - name: Setup Hetzner Cloud
        uses: hetznercloud/setup-hcloud@v1

      - name: Remove old snapshots
        run: |
          hcloud image list -t snapshot -o json | jq -r '[.[] | select(.created | fromdateiso8601 < (now - 7*24*60*60))] | sort_by(.created) | .[:-1] | .[].id' | while read -r snapshot_id; do
            echo "Removing snapshot with ID: $snapshot_id"
            hcloud image delete "$snapshot_id"
          done
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}