name: plan-prod

concurrency:
  group: terraform-prod-plan

on:
  pull_request_target:
    branches:
      - main
    paths:
      - "**.tf"
      - "**.tfvars"
      - "**.yaml"
      - "**.yml"

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: "read" # needed for gcp_auth
      id-token: "write" # needed for gcp_auth to create id token
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_TERRAFORM_PLANNER_SERVICE_ACCOUNT_EMAIL }}

      - id: "secrets"
        uses: "google-github-actions/get-secretmanager-secrets@v2"
        with:
          secrets: |-
            tf-planner-gh-token:${{ vars.GCP_PROJECT_ID }}/terraform-planner-gh-token
            tf-planner-hcloud-token:${{ vars.GCP_PROJECT_ID }}/terraform-planner-hcloud-token
            tf-planner-cf-token:${{ vars.GCP_PROJECT_ID }}/terraform-planner-cloudflare-token

      - name: Tofu Init
        run: tofu init -input=false
        working-directory: terraform/environments/prod

      - name: Tofu Validate
        env:
          GITHUB_TOKEN: ${{ steps.secrets.outputs.tf-planner-gh-token }}
          CLOUDFLARE_API_TOKEN: ${{ steps.secrets.outputs.tf-executor-cf-token }}
          TF_VAR_hcloud_token: ${{ steps.secrets.outputs.tf-executor-hcloud-token }}
          TF_VAR_ssh_public_key: ${{ vars.TF_SSH_PUBLIC_KEY }}
          TF_VAR_ssh_private_key: ${{ steps.secrets.outputs.tf-ssh-private-key }}
        run: tofu validate -no-color
        working-directory: terraform/environments/prod

      - name: Tofu Plan
        run: tofu plan -input=false -no-color -lock-timeout=300s
        timeout-minutes: 120
        env:
          GITHUB_TOKEN: ${{ steps.secrets.outputs.tf-planner-gh-token }}
          CLOUDFLARE_API_TOKEN: ${{ steps.secrets.outputs.tf-executor-cf-token }}
          TF_VAR_hcloud_token: ${{ steps.secrets.outputs.tf-executor-hcloud-token }}
          TF_VAR_ssh_public_key: ${{ vars.TF_SSH_PUBLIC_KEY }}
          TF_VAR_ssh_private_key: ${{ steps.secrets.outputs.tf-ssh-private-key }}
        working-directory: terraform/environments/prod
