name: plan-prod

concurrency:
  group: terraform-prod

on:
  pull_request_target:
    branches:
      - main
    paths:
      - "**.tf"
      - "**.tfvars"
      - "**.yaml"
      - "**.yml"

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: "read" # needed for gcp_auth
      id-token: "write" # needed for gcp_auth to create id token
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      TF_VAR_argo_github_token: ${{ secrets.ARGO_GITHUB_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Verify if PR is mergeable
        id: pr-check
        run: |
          if [[ -z "${{ github.event.pull_request.merge_commit_sha }}" ]]; then
            echo "This PR is not mergeable. Exiting."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      # Important security check: https://github.com/actions/checkout/issues/518
      - name: Sanity check
        id: sanity-check
        run: |
          [[ "$(git rev-parse 'HEAD^1')" == "${{ github.event.pull_request.head.sha }}" || "$(git rev-parse 'HEAD^2')" == "${{ github.event.pull_request.head.sha }}" ]]
        if: ${{ github.event_name == 'pull_request_target' || github.event_name == 'pull_request' }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_TERRAFORM_PLANNER_SERVICE_ACCOUNT_EMAIL }}

      - name: Tofu Init
        run: tofu init -input=false
        working-directory: terraform/environments/prod

      - name: Tofu Validate
        run: tofu validate -no-color
        working-directory: terraform/environments/prod

      - name: Tofu Plan
        run: tofu plan -input=false -no-color -lock-timeout=300s
        working-directory: terraform/environments/prod