- name: Install and configure Docker
  hosts: all
  become: true
  pre_tasks:
    - name: Update all packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        force: true
  tasks:
    - name: Install docker packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - python3-docker
        - python3-jsondiff
      tags:
        - docker

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present
      tags:
        - docker

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} stable"
        state: present
        update_cache: true
      tags:
        - docker

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      tags:
        - docker

    - name: Install Docker CE
      ansible.builtin.apt:
        name: docker-ce
        state: present
      tags:
        - docker

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        group: docker
        append: true
      tags:
        - docker

    - name: Install docker-compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "u+x,g+x"
