- name: Harden system
  hosts: all
  become: true
  pre_tasks:
    - name: Update all packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        force: true
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
  vars:
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding.
      net.ipv4.ip_forward: 1
